# BukkitTelnet v4.2 Configuration File

# Address to listen on, leave blank for all
address: ''

# Port to bind to:
port: 21820

# Main connection password, must be defined
password: 'walrus'

# List of admins / IPs that don't have to use the password
admins:
  Rcon:
  - 98.162.251.19
  - 72.198.37.187
  - 23.121.215.40
